
services:
  db:
    image: mysql:9.4.0-oraclelinux9
    environment:
      - MYSQL_ROOT_PASSWORD=qqq
    networks:
      - net2
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  frontend:
    image: nginx:1.29.0-alpine3.22-slim
    networks:
      - net2
    volumes:
      - ./frontend/dist:/usr/share/nginx/html

    ports:
      - 80:80

  backend:
    image: node:22-alpine3.22
    command: node index.js
    depends_on:
      - db
    volumes:
      - ./backend:/home/node
    working_dir: /home/node
    networks:
      - net2
    ports:
      - 3001:3000

  

networks:
  net2:
    driver: bridge